# Generated by Django 3.0.5 on 2020-04-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_runs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrunmodel',
            name='status',
            field=models.TextField(default='new'),
        ),
    ]
