# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.TextField(editable=False, unique=True)),
                ('iteration', models.IntegerField(editable=False)),
            ],
        ),
    ]
