apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: jenkins-worker-pod
    app.kubernetes.io/instance: jenkins-worker-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - cat
    tty: true