apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins/kube-default: true
    app: jenkins
    component: agent
spec:
  containers:
  - name: dind
    image: docker:19-dind
    securityContext:
      privileged: true
    volumeMounts:
      - name: dind-storage
        mountPath: /var/lib/docker
    resources:
      requests:
        cpu: "200m"
  volumes:
  - name: dind-storage
    emptyDir: {}
