# Compose file used for production
# Relies on base.yml, but specifies links and ports
version: "2"
services:
  learning:
    extends:
      file: base.yml
      service: learning

  server:
    extends:
      file: base.yml
      service: server

  ui:
    extends:
      file: base.yml
      service: ui
    volumes_from:
      - server

  db:
    extends:
      file: base.yml
      service: db
    ports:
      - "5432"

volumes:
  media:
  pgdata:
  static:

networks:
  main:
