# JS container for running dev server
# TODO (jordan) Look into DRYing this & Dockerfile out w/ Docker Buildkit
FROM node:13-alpine
WORKDIR /js_app

# Install system packages for dev tooling
RUN apk add --no-cache bash

# Install React dependencies
COPY js/yarn.lock .
COPY js/package.json .
RUN yarn install --pure-lockfile

# Copy configs for tooling
COPY js/.prettierrc .
COPY js/jest.config.js .
COPY js/tsconfig.json .
COPY js/.storybook ./.storybook

CMD ["yarn", "start"]
