# JS container for running dev server
# TODO (jordan) Look into DRYing this & Dockerfile out w/ Docker Buildkit
FROM node:alpine
WORKDIR /js_app

# Install React dependencies
COPY js/yarn.lock .
COPY js/package.json .
RUN yarn install --pure-lockfile

# Copy prettier & storybook configs
COPY js/.prettierrc .
COPY js/jest.config.js .
COPY js/tsconfig.json .
COPY js/.storybook ./.storybook

CMD ["yarn", "start"]
